# Generated by Django 4.2.2 on 2024-01-07 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LSP',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('lsp_type', models.CharField(max_length=100)),
                ('display_picture', models.ImageField(blank=True, upload_to='lsp_display_pics/')),
                ('signature', models.ImageField(blank=True, upload_to='lsp_signature/')),
                ('enrollment_number', models.CharField(max_length=50, unique=True)),
                ('bar_council_practicing_certificate', models.FileField(blank=True, upload_to='bar_council_certificates/')),
                ('enrollment_year', models.IntegerField()),
                ('university_llb_completed', models.CharField(max_length=100)),
                ('llb_passout_year', models.IntegerField()),
            ],
        ),
    ]
