# Generated by Django 4.2.2 on 2024-01-10 15:42

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_lsp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lsp',
            name='bar_council_practicing_certificate',
            field=models.FileField(blank=True, upload_to=accounts.models.LSP.upload_path),
        ),
        migrations.AlterField(
            model_name='lsp',
            name='display_picture',
            field=models.ImageField(blank=True, upload_to=accounts.models.LSP.upload_path),
        ),
        migrations.AlterField(
            model_name='lsp',
            name='signature',
            field=models.ImageField(blank=True, upload_to=accounts.models.LSP.upload_path),
        ),
    ]
