# Generated by Django 4.2.1 on 2024-01-20 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_fileupload_friend_msg'),
    ]

    operations = [
        migrations.AddField(
            model_name='msg',
            name='encrypted_message',
            field=models.BinaryField(default=b''),
        ),
    ]
